In [80]:
import pandas as pd

In [81]:
series = pd.Series([10.5, 20, 30], index=['a', 'b', 'c'], name='Sales')
series

a    10.5
b    20.0
c    30.0
Name: Sales, dtype: float64

In [82]:
df = pd.DataFrame({
    'name': ["Alice", "Bob", "John", "Doe"],
    'age': [20, 12, 30, 23],
    'city': ['LA', 'NY', 'CA', 'NY']
})
df

    name  age city
0  Alice   20   LA
1    Bob   12   NY
2   John   30   CA
3    Doe   23   NY

In [83]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [84]:
df.columns

Index(['name', 'age', 'city'], dtype='object')

In [85]:
df.values

array([['Alice', 20, 'LA'],
       ['Bob', 12, 'NY'],
       ['John', 30, 'CA'],
       ['Doe', 23, 'NY']], dtype=object)

In [86]:
df.dtypes

name    object
age      int64
city    object
dtype: object

In [87]:
pd.DataFrame([[1, 2], [3, 4]], columns=['a', 'b'])

   a  b
0  1  2
1  3  4

In [ ]:
## Read the Data
pd.read_csv("abc.csv", sep=':', nrows=100, encoding='UTF-8')
pd.read_excel("abc.xlsx")
pd.read_json("abc.json")

In [ ]:
## Writing the Data

df.to_csv("out.csv", index=False)
df.to_excel("out.xlsx", index=False)
df.to_json("out.json")

In [91]:
df = pd.DataFrame({
    'name': ["Alice", "Bob", "John", "Doe", "Himmat", "Kathy", "Bobin"],
    'age': [20, 12, 30, 23, 21, 23, 32],
    'city': ['LA', 'NY', 'CA', 'NY', 'LA', 'CA', 'NY']
})
df

     name  age city
0   Alice   20   LA
1     Bob   12   NY
2    John   30   CA
3     Doe   23   NY
4  Himmat   21   LA
5   Kathy   23   CA
6   Bobin   32   NY

In [92]:
df.head(n=3)

    name  age city
0  Alice   20   LA
1    Bob   12   NY
2   John   30   CA

In [93]:
df.tail(n=3)

     name  age city
4  Himmat   21   LA
5   Kathy   23   CA
6   Bobin   32   NY

In [94]:
df.shape

(7, 3)

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    7 non-null      object
 1   age     7 non-null      int64
 2   city    7 non-null      object
dtypes: int64(1), object(2)
memory usage: 300.0+ bytes

In [96]:
df.describe()

            age
count   7.00000
mean   23.00000
std     6.63325
min    12.00000
25%    20.50000
50%    23.00000
75%    26.50000
max    32.00000

In [97]:
df.describe(include='all')

         name       age city
count       7   7.00000    7
unique      7       NaN    3
top     Alice       NaN   NY
freq        1       NaN    3
mean      NaN  23.00000  NaN
std       NaN   6.63325  NaN
min       NaN  12.00000  NaN
25%       NaN  20.50000  NaN
50%       NaN  23.00000  NaN
75%       NaN  26.50000  NaN
max       NaN  32.00000  NaN

In [98]:
df.dtypes, df.columns, df.values

(name    object
 age      int64
 city    object
 dtype: object,
 Index(['name', 'age', 'city'], dtype='object'),
 array([['Alice', 20, 'LA'],
        ['Bob', 12, 'NY'],
        ['John', 30, 'CA'],
        ['Doe', 23, 'NY'],
        ['Himmat', 21, 'LA'],
        ['Kathy', 23, 'CA'],
        ['Bobin', 32, 'NY']], dtype=object))

In [99]:
df.nunique()

name    7
age     6
city    3
dtype: int64

In [100]:
df['city'].value_counts()

city
NY    3
LA    2
CA    2
Name: count, dtype: int64

In [101]:
df.sample(4)

     name  age city
2    John   30   CA
4  Himmat   21   LA
6   Bobin   32   NY
5   Kathy   23   CA

In [102]:
df.memory_usage(deep=True)

Index    132
name     374
age       56
city     357
dtype: int64

In [103]:
df[['name', 'age']]

     name  age
0   Alice   20
1     Bob   12
2    John   30
3     Doe   23
4  Himmat   21
5   Kathy   23
6   Bobin   32

In [104]:
df

     name  age city
0   Alice   20   LA
1     Bob   12   NY
2    John   30   CA
3     Doe   23   NY
4  Himmat   21   LA
5   Kathy   23   CA
6   Bobin   32   NY

In [105]:
df.loc[2:6, ['city', 'name']]

  city    name
2   CA    John
3   NY     Doe
4   LA  Himmat
5   CA   Kathy
6   NY   Bobin

In [106]:
df.iloc[0:2, 0:3]

    name  age city
0  Alice   20   LA
1    Bob   12   NY

In [107]:
df[df['age'] > 25]

    name  age city
2   John   30   CA
6  Bobin   32   NY

In [108]:
df[(df['age'] > 10) & (df['city'] == 'NY')]

    name  age city
1    Bob   12   NY
3    Doe   23   NY
6  Bobin   32   NY

In [109]:
df[(df['age'] >= 20) | (df['city'] == 'LA')]

     name  age city
0   Alice   20   LA
2    John   30   CA
3     Doe   23   NY
4  Himmat   21   LA
5   Kathy   23   CA
6   Bobin   32   NY

In [110]:
df[~(df['age'] > 25)]

     name  age city
0   Alice   20   LA
1     Bob   12   NY
3     Doe   23   NY
4  Himmat   21   LA
5   Kathy   23   CA

In [111]:
df['salary'] = df['age'] ** 2

In [112]:
df.head(3)

    name  age city  salary
0  Alice   20   LA     400
1    Bob   12   NY     144
2   John   30   CA     900

In [113]:
import numpy as np

In [114]:
df['category'] = np.where(df['age'] > 25, 'old', 'young')

In [115]:
df

     name  age city  salary category
0   Alice   20   LA     400    young
1     Bob   12   NY     144    young
2    John   30   CA     900      old
3     Doe   23   NY     529    young
4  Himmat   21   LA     441    young
5   Kathy   23   CA     529    young
6   Bobin   32   NY    1024      old

In [116]:
df = df.rename(columns={'age': 'years'})

In [117]:
df.head(2)

    name  years city  salary category
0  Alice     20   LA     400    young
1    Bob     12   NY     144    young

In [118]:
df = df.drop(columns=['salary'])
df.head(2)

    name  years city category
0  Alice     20   LA    young
1    Bob     12   NY    young

In [119]:
df = df.drop(index=[0, 1])
df.head(6)

     name  years city category
2    John     30   CA      old
3     Doe     23   NY    young
4  Himmat     21   LA    young
5   Kathy     23   CA    young
6   Bobin     32   NY      old

In [121]:
df.isnull().sum(), df.isna().sum()

(name        0
 years       0
 city        0
 category    0
 dtype: int64,
 name        0
 years       0
 city        0
 category    0
 dtype: int64)

In [123]:
df.dropna(), df.dropna(axis=1), df.dropna(subset=['years'])

(     name  years city category
 2    John     30   CA      old
 3     Doe     23   NY    young
 4  Himmat     21   LA    young
 5   Kathy     23   CA    young
 6   Bobin     32   NY      old,
      name  years city category
 2    John     30   CA      old
 3     Doe     23   NY    young
 4  Himmat     21   LA    young
 5   Kathy     23   CA    young
 6   Bobin     32   NY      old,
      name  years city category
 2    John     30   CA      old
 3     Doe     23   NY    young
 4  Himmat     21   LA    young
 5   Kathy     23   CA    young
 6   Bobin     32   NY      old)

In [ ]:
df.fillna(0)
df.fillna({'year': df['year'].mean(), 'city': 'Unknown'})
df.fillna(df['years'].mean(), inplace=True)

In [ ]:
df['years'] = df['years'].astype(int)
df['date'] = pd.to_datetime(df['date'])
df['price'] = pd.to_numeric(df['price'], errors='coerce')

In [130]:
df.sort_values('years', ascending=False)

     name  years city category
6   Bobin     32   NY      old
2    John     30   CA      old
3     Doe     23   NY    young
5   Kathy     23   CA    young
4  Himmat     21   LA    young

In [132]:
df.sort_index(ascending=False)

     name  years city category
6   Bobin     32   NY      old
5   Kathy     23   CA    young
4  Himmat     21   LA    young
3     Doe     23   NY    young
2    John     30   CA      old

In [135]:
df.nlargest(4, 'years')

    name  years city category
6  Bobin     32   NY      old
2   John     30   CA      old
3    Doe     23   NY    young
5  Kathy     23   CA    young

In [138]:
df = df.rename(columns={'years': 'age'})

In [141]:
df.groupby('city')['age'].mean()

city
CA    26.5
LA    21.0
NY    27.5
Name: age, dtype: float64

In [142]:
df.groupby('city').agg({
    'age': 'mean',
    'name': 'count'
})

       age  name
city
CA    26.5     2
LA    21.0     1
NY    27.5     2

In [144]:
df.groupby(['city', 'age']).size()

city  age
CA    23     1
      30     1
LA    21     1
NY    23     1
      32     1
dtype: int64

In [147]:
df.groupby('city').apply(lambda x: x.nlargest(2, 'age'))

/var/folders/2n/19c5d_cd4tz_tpj4b7g93jxc0000gn/T/ipykernel_1023/2921466668.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df.groupby('city').apply(lambda x: x.nlargest(2, 'age'))

          name  age city category
city
CA   2    John   30   CA      old
     5   Kathy   23   CA    young
LA   4  Himmat   21   LA    young
NY   6   Bobin   32   NY      old
     3     Doe   23   NY    young

In [ ]:
# pd.merge(df1, df2, on='id', how='lef')

In [148]:
df.duplicated().sum()

np.int64(0)

In [151]:
df.drop_duplicates(inplace=True)

In [152]:
# pd.concat([df1, df2], ignore_index=True)