In [73]:
import numpy as np
import pandas as pd

In [74]:
df = pd.read_csv("messy_employee_data.csv")
df.head()

,employee_id,full_name,age,city,department,salary,join_date,email,rating,is_active
0,38,Jack Martinez,27.0,Kathmandu,Finance,86148,21-09-2016,NaN,NaN,yes
1,27,Jack Miller,NaN,Phoenix,Finance,"$46,683",11/13/2021,jack.miller@company.com,2.2,yes
2,79,Emma Williams,NaN,Los Angeles,Marketing,NaN,NaN,emma.williams@company.com,NaN,Yes
3,79,Emma Williams,NaN,Los Angeles,Marketing,NaN,NaN,emma.williams@company.com,NaN,Yes
4,50,Sam Martinez,NaN,New York,Engineering,NaN,NaN,sam.martinez@company.com,NaN,no

In [75]:
df.tail()

,employee_id,full_name,age,city,department,salary,join_date,email,rating,is_active
95,84,Quinn Brown,NaN,Chicago,Engineering,"$43,474",04/06/2019,quinn.brown@company.com,NaN,no
96,68,Paul Martinez,46.0,Kathmandu,Engineering,NaN,04-06-2018,paul.martinez@company.com,NaN,yes
97,26,Sam Brown,NaN,Delhi,Sales,"$98,146",03-07-2020,sam.brown@company.com,NaN,True
98,69,Grace Johnson,NaN,Houston,Support,113819,06/08/2015,grace.johnson@company.com,4.3,True
99,48,Henry Jones,NaN,Houston,HR,"$45,043",05/27/2017,NaN,NaN,no

In [76]:
df.shape

(100, 10)

In [77]:
df.columns

Index(['employee_id', 'full_name', 'age', 'city', 'department', 'salary',
       'join_date', 'email', 'rating', 'is_active'],
      dtype='object')

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   employee_id  100 non-null    int64
 1   full_name    100 non-null    object
 2   age          57 non-null     float64
 3   city         91 non-null     object
 4   department   100 non-null    object
 5   salary       64 non-null     object
 6   join_date    65 non-null     object
 7   email        91 non-null     object
 8   rating       48 non-null     float64
 9   is_active    80 non-null     object
dtypes: float64(2), int64(1), object(7)
memory usage: 7.9+ KB

In [79]:
df.describe(include='all')

,employee_id,full_name,age,city,department,salary,join_date,email,rating,is_active
count,100.000000,100,57.000000,91,100,64,65,91,48.000000,80
unique,NaN,70,NaN,8,6,57,61,67,NaN,6
top,NaN,Paul Johnson,NaN,Delhi,Finance,"$78,843",2020-11-20,rita.miller@company.com,NaN,no
freq,NaN,5,NaN,18,24,2,2,3,NaN,20
mean,45.930000,NaN,38.754386,NaN,NaN,NaN,NaN,NaN,2.887500,NaN
std,25.785931,NaN,10.690919,NaN,NaN,NaN,NaN,NaN,1.055205,NaN
min,1.000000,NaN,20.000000,NaN,NaN,NaN,NaN,NaN,1.000000,NaN
25%,23.750000,NaN,29.000000,NaN,NaN,NaN,NaN,NaN,2.175000,NaN
50%,46.500000,NaN,37.000000,NaN,NaN,NaN,NaN,NaN,2.900000,NaN
75%,67.250000,NaN,49.000000,NaN,NaN,NaN,NaN,NaN,3.800000,NaN
max,90.000000,NaN,58.000000,NaN,NaN,NaN,NaN,NaN,4.800000,NaN

In [80]:
df.duplicated().sum()

np.int64(8)

In [81]:
df.drop_duplicates(inplace=True)

In [82]:
df.isnull().sum()

employee_id     0
full_name       0
age            38
city            9
department      0
salary         33
join_date      30
email           8
rating         46
is_active      19
dtype: int64

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 92 entries, 0 to 99
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   employee_id  92 non-null     int64
 1   full_name    92 non-null     object
 2   age          54 non-null     float64
 3   city         83 non-null     object
 4   department   92 non-null     object
 5   salary       59 non-null     object
 6   join_date    62 non-null     object
 7   email        84 non-null     object
 8   rating       46 non-null     float64
 9   is_active    73 non-null     object
dtypes: float64(2), int64(1), object(7)
memory usage: 7.9+ KB

In [84]:
df['age'] = pd.to_numeric(df['age'], errors='coerce')

In [85]:
df['salary'] = df['salary'].astype(str).str.replace('[$]', '', regex=True)

In [86]:
df['salary'] = pd.to_numeric(df['salary'], errors='coerce')

In [87]:
df['join_date'] = pd.to_datetime(df['join_date'], format='mixed', errors='coerce')

In [88]:
df['is_active'] = df['is_active'].str.lower().map({
    'yes': True,
    'No': False,
    'true':True,
    'false': False
})

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 92 entries, 0 to 99
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   employee_id  92 non-null     int64
 1   full_name    92 non-null     object
 2   age          54 non-null     float64
 3   city         83 non-null     object
 4   department   92 non-null     object
 5   salary       38 non-null     float64
 6   join_date    62 non-null     datetime64[ns]
 7   email        84 non-null     object
 8   rating       46 non-null     float64
 9   is_active    48 non-null     object
dtypes: datetime64[ns](1), float64(3), int64(1), object(5)
memory usage: 7.9+ KB

In [90]:
df.isnull().sum()

employee_id     0
full_name       0
age            38
city            9
department      0
salary         54
join_date      30
email           8
rating         46
is_active      44
dtype: int64

In [91]:
df.fillna({
    'age': df['age'].mean(),
    'city': df['city'].mode()[0],
    'email': 'unknown@gmail.com',
    'salary': df['salary'].median(),
    'join_date': 0000-00-00,
    'rating': df['rating'].mean(),
    'is_active': df['is_active'].mode()[0]
}, inplace=True)

/var/folders/2n/19c5d_cd4tz_tpj4b7g93jxc0000gn/T/ipykernel_3045/2897849723.py:1: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.fillna({

In [92]:
df.isnull().sum()

employee_id    0
full_name      0
age            0
city           0
department     0
salary         0
join_date      0
email          0
rating         0
is_active      0
dtype: int64

In [93]:
df['is_active'].unique()

array([ True, False])

In [95]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 92 entries, 0 to 99
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   employee_id  92 non-null     int64
 1   full_name    92 non-null     object
 2   age          92 non-null     float64
 3   city         92 non-null     object
 4   department   92 non-null     object
 5   salary       92 non-null     float64
 6   join_date    92 non-null     object
 7   email        92 non-null     object
 8   rating       92 non-null     float64
 9   is_active    92 non-null     bool
dtypes: bool(1), float64(3), int64(1), object(5)
memory usage: 7.3+ KB

In [ ]:
df.loc[0:10]

,employee_id,full_name,age,city,department,salary,join_date,email,rating,is_active
0,38,Jack Martinez,27.000000,Kathmandu,Finance,86148.0,2016-09-21 00:00:00,unknown@gmail.com,2.880435,True
1,27,Jack Miller,38.981481,Phoenix,Finance,87809.0,2021-11-13 00:00:00,jack.miller@company.com,2.200000,True
2,79,Emma Williams,38.981481,Los Angeles,Marketing,87809.0,0,emma.williams@company.com,2.880435,True
4,50,Sam Martinez,38.981481,New York,Engineering,87809.0,0,sam.martinez@company.com,2.880435,True
5,16,Grace Jones,38.981481,Delhi,Sales,71104.0,2015-10-16 00:00:00,unknown@gmail.com,3.000000,True
6,56,Rita Miller,49.000000,Houston,Finance,87809.0,0,rita.miller@company.com,2.500000,True
7,72,Quinn Brown,38.981481,Delhi,Marketing,90036.0,0,quinn.brown@company.com,2.880435,True
8,87,Sam Brown,58.000000,Delhi,Engineering,87809.0,2016-06-23 00:00:00,sam.brown@company.com,2.880435,True
9,23,Emma Brown,31.000000,New York,Engineering,87809.0,2018-05-06 00:00:00,emma.brown@company.com,2.900000,True
10,14,Nate Williams,37.000000,Los Angeles,HR,102132.0,2015-11-18 00:00:00,nate.williams@company.com,4.400000,True

In [97]:
df.iloc[0:10, 0:4]

    employee_id      full_name        age         city
0            38  Jack Martinez  27.000000    Kathmandu
1            27    Jack Miller  38.981481      Phoenix
2            79  Emma Williams  38.981481  Los Angeles
4            50   Sam Martinez  38.981481     New York
5            16    Grace Jones  38.981481        Delhi
6            56    Rita Miller  49.000000      Houston
7            72    Quinn Brown  38.981481        Delhi
8            87      Sam Brown  58.000000        Delhi
9            23     Emma Brown  31.000000     New York
10           14  Nate Williams  37.000000  Los Angeles

In [98]:
df.groupby(['city', 'department'])['age'].mean()

city         department
Chicago      Engineering    33.990741
             Finance        32.666667
             HR             33.000000
             Marketing      58.000000
             Sales          29.000000
             Support        37.990741
Delhi        Engineering    38.245370
             Finance        40.327160
             HR             35.490741
             Marketing      39.327160
             Sales          33.388889
             Support        35.987654
Houston      Engineering    53.000000
             Finance        44.490741
             HR             38.981481
             Marketing      38.981481
             Support        38.981481
Kathmandu    Engineering    46.000000
             Finance        32.000000
             HR             46.490741
             Marketing      30.000000
             Sales          37.490741
             Support        38.981481
London       Engineering    38.981481
             Finance        38.981481
             HR             53.000000
             Marketing      46.333333
Los Angeles  Engineering    36.000000
             Finance        42.000000
             HR             44.327160
             Marketing      38.981481
             Sales          49.000000
             Support        26.000000
New York     Engineering    39.660494
             Finance        38.981481
             Marketing      43.990741
             Sales          34.000000
             Support        42.500000
Phoenix      Engineering    20.000000
             Finance        38.981481
             HR             37.993827
             Sales          39.236111
             Support        38.981481
Name: age, dtype: float64

In [99]:
df.groupby(['city', 'department'])['salary'].mean()

city         department
Chicago      Engineering     95694.000000
             Finance         76852.333333
             HR              87809.000000
             Marketing      111830.000000
             Sales           70404.000000
             Support         68887.000000
Delhi        Engineering     88224.250000
             Finance         85191.333333
             HR              87809.000000
             Marketing       88180.166667
             Sales           88870.600000
             Support         90186.666667
Houston      Engineering     38392.000000
             Finance         92837.750000
             HR              87809.000000
             Marketing       87809.000000
             Support         84128.666667
Kathmandu    Engineering     87809.000000
             Finance         86978.500000
             HR              60180.500000
             Marketing       87809.000000
             Sales           84763.000000
             Support         87809.000000
London       Engineering     87809.000000
             Finance         69726.000000
             HR              87809.000000
             Marketing      107102.000000
Los Angeles  Engineering     70768.000000
             Finance        100155.500000
             HR              80582.000000
             Marketing       87809.000000
             Sales           90068.000000
             Support         61542.500000
New York     Engineering     91190.000000
             Finance         87809.000000
             Marketing       77718.000000
             Sales           87809.000000
             Support        101729.000000
Phoenix      Engineering     87809.000000
             Finance        101763.000000
             HR              96312.666667
             Sales           82624.750000
             Support         68696.000000
Name: salary, dtype: float64

In [100]:
df.head()

,employee_id,full_name,age,city,department,salary,join_date,email,rating,is_active
0,38,Jack Martinez,27.000000,Kathmandu,Finance,86148.0,2016-09-21 00:00:00,unknown@gmail.com,2.880435,True
1,27,Jack Miller,38.981481,Phoenix,Finance,87809.0,2021-11-13 00:00:00,jack.miller@company.com,2.200000,True
2,79,Emma Williams,38.981481,Los Angeles,Marketing,87809.0,0,emma.williams@company.com,2.880435,True
4,50,Sam Martinez,38.981481,New York,Engineering,87809.0,0,sam.martinez@company.com,2.880435,True
5,16,Grace Jones,38.981481,Delhi,Sales,71104.0,2015-10-16 00:00:00,unknown@gmail.com,3.000000,True

In [103]:
df.groupby('department')['rating'].mean()

department
Engineering    2.853106
Finance        2.609190
HR             3.312542
Marketing      3.037536
Sales          2.737422
Support        2.907453
Name: rating, dtype: float64

In [104]:
df.groupby('city')['rating'].mean()

city
Chicago        2.858261
Delhi          2.794816
Houston        3.044130
Kathmandu      2.960386
London         3.045963
Los Angeles    2.512174
New York       2.898068
Phoenix        3.103755
Name: rating, dtype: float64

In [110]:
df.groupby('department')['is_active'].value_counts()

department   is_active
Engineering  True         14
Finance      True         19
             False         3
HR           True         10
             False         3
Marketing    True         13
             False         2
Sales        True         13
             False         1
Support      True         12
             False         2
Name: count, dtype: int64